dist: trusty
sudo: required
language: node_js
os:
  - linux

env:
  global:
    - DBUS_SESSION_BUS_ADDRESS=/dev/null
    - DISPLAY=:99.0
    - CHROME_BIN=chromium-browser
    - SAUCE_ACCESS_KEY=72e4f85f-4e6b-4971-b8c5-f6707308f63e
    - SAUCE_USERNAME="mgiambalvo"
    - SAUCE_CONNECT_VERSION="4.4.0"
  matrix:
    - CI_MODE=local
    - CI_MODE=saucelabs

cache:
  directories:
    - tour-of-heroes/node_modules

install:
  - cd tour-of-heroes
  - npm install

before_script:
  - ./scripts/travis_setup.sh

script:
  - npm run lint
  - npm run test -- --watch=false
  - npm run travis
